branches: {only: [master]}

sudo: false
cache: pip
language: python

matrix:
  include:
    - {env: TOXENV=style, python: "3.4"}
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"

install:
  - pip install tox-travis
  - pip install coveralls
  - pip install -U pip setuptools

script: tox -v

after_success: coveralls
