sudo: false
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=django~=1.8.0
  - DJANGO=django~=1.9.0
  - DJANGO=django~=1.10.0
install:
  - pip install -U pip
  - "pip install $DJANGO coveralls -e .[dev]"
script:
  - flake8 analog
  - py.test -vvv --cov
after_success: coveralls
